spring.application.name=CodeArena
spring.datasource.url=jdbc:mysql://localhost:3306/codearena_db
spring.datasource.username=root
spring.datasource.password=ankur@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true